rm -rf site/wwwroot/favicon.ico
rm -rf site/wwwroot/index.html
rm -rf site/wwwroot/vendor.bundle.js
rm -rf site/wwwroot/vendor.bundle.map
rm -rf site/wwwroot/styles.bundle.map
rm -rf site/wwwroot/styles.bundle.css
rm -rf site/wwwroot/main.bundle.map
rm -rf site/wwwroot/main.bundle.js
rm -rf site/wwwroot/inline.bundle.map
rm -rf site/wwwroot/inline.bundle.js
