rm -rf favicon.ico
rm -rf index.html
rm -rf vendor.bundle.js
rm -rf vendor.bundle.map
rm -rf styles.bundle.map
rm -rf styles.bundle.css
rm -rf main.bundle.map
rm -rf main.bundle.js
rm -rf inline.bundle.map
rm -rf inline.bundle.js
